version: "3.7"

services:
  dev:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    command: sleep 10d
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
      - 9229:9229

  prod:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: prod
